version: "3.0"

services:

    transaction-api:
      build:
        context: ./transaction-api
        dockerfile: Dockerfile
      environment: 
        - "ArchChallengeProjectDatabaseSettings:ConnectionString=mongodb://arch:arch@mongodb"
        - "ConnectionStrings:RedisConnectionString=redis:6379"
      container_name: transaction-api
      restart: always
      ports:
        - 5000:80
      depends_on:
        - redis
        - mongodb
      networks:
        - transaction-network

    balance-api:
      build:
        context: ./balance-api
        dockerfile: Dockerfile
      environment: 
        - "ArchChallengeProjectDatabaseSettings:ConnectionString=mongodb://arch:arch@mongodb"
        - "ConnectionStrings:RedisConnectionString=redis:6379"
      container_name: balance-api
      restart: always
      ports:
        - 5001:80
      depends_on:
        - redis
        - mongodb
      networks:
        - balance-network

    redis:
      container_name: redis
      image: redis:alpine
      restart: always
      ports:
        - 6379
      volumes: 
        - arch-db:/data
      networks:
        - redis-network
        - transaction-network
        - balance-network

    redis-commander:
      container_name: redis-commander
      image: rediscommander/redis-commander:latest
      restart: always
      environment:
        REDIS_HOST: redis
        REDIS_PORT: 6379
        PORT: 8082
      ports:
        - 8082:8082
      networks:
        - redis-network

    mongodb:
      container_name: mongodb
      image: mongo:5.0
      environment:
        MONGO_INITDB_ROOT_USERNAME: arch
        MONGO_INITDB_ROOT_PASSWORD: arch
      restart: always
      ports:
        - 27017
      volumes:
        - arch-db:/data/db mongo
      networks:
        - mongo-network
        - transaction-network
        - balance-network

    mongo-express:
      container_name: mongo-express
      image: mongo-express:0.54.0
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: arch
        ME_CONFIG_MONGODB_ADMINPASSWORD: arch
        ME_CONFIG_MONGODB_SERVER: mongodb
        ME_CONFIG_MONGODB_PORT: 27017
      restart: always
      ports:
        - 8081:8081
      depends_on:
        - mongodb
      networks:
        - mongo-network

volumes:
  arch-db:
    driver: local
  arch-cache:
    driver: local

networks:
  transaction-network:
    driver: bridge
  balance-network:
    driver: bridge
  redis-network:
    driver: bridge
  mongo-network:
    driver: bridge
